import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import AppShell from "@/components/layout/AppShell";
import QueryProvider from "@/providers/QueryProvider";
import AuthProvider from "@/providers/AuthProvider";

const GA_ID = "G-5C1B8HQXBX";

const SITE_URL = "https://gyoan-maker.store";

export const metadata: Metadata = {
  title: {
    default: "GyoanMaker | AI 영어 교안 자동 생성",
    template: "%s | GyoanMaker",
  },
  description:
    "영어 지문을 입력하면 AI가 문장 분석, 핵심 어휘, 요약까지 자동 생성합니다. 인쇄용 PDF로 바로 출력하세요.",
  keywords: [
    "영어 교안",
    "AI 교안 생성",
    "영어 지문 분석",
    "학원 교안",
    "PDF 교안",
    "영어 어휘 분석",
  ],
  metadataBase: new URL(SITE_URL),
  alternates: { canonical: "/" },
  openGraph: {
    title: "GyoanMaker | AI 영어 교안 자동 생성",
    description:
      "영어 지문 분석부터 교안 출력까지, 한 번에. AI가 문장 분석·어휘·요약을 자동 생성합니다.",
    url: SITE_URL,
    siteName: "GyoanMaker",
    locale: "ko_KR",
    type: "website",
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_ID}');
          `}
        </Script>
        <AuthProvider>
          <QueryProvider>
            <AppShell>{children}</AppShell>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
